@core_host=localhost:84
@dialogs_host=localhost:80
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBZG1pbiIsImdpdmVuX25hbWUiOiJBZG1pbiIsImZhbWlseV9uYW1lIjoiQWRtaW4iLCJqdGkiOiI1NjgzZTAyNS04MWJkLTRjODMtODNkMy1mOTUyMzk0MmE1N2YiLCJleHAiOjIwNDIzMzQzOTksImlzcyI6IkhpZ2hsb2FkU29jaWFsIiwiYXVkIjoiSGlnaGxvYWRTb2NpYWwifQ.i2CnhTDvw_l8KPyNQNfqJZ_d40OvoGqpiO8dRrFRJOY
### Login
POST http://{{core_host}}/login
Content-Type: application/json

{
  "id": "Admin",
  "password": "password"
}


### SendMessage
POST http://{{dialogs_host}}/dialog/LadyGaga/send
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Sup Lady Gaga 1 2 3 4"
}

### ListDialogs
GET http://{{dialogs_host}}/dialog/list
Content-Type: application/json
Authorization: Bearer {{token}}

### ListMessages
GET http://{{dialogs_host}}/dialog/User/list
Content-Type: application/json
Authorization: Bearer {{token}}