@core_host=localhost:8080
@dialogs_host=localhost:8180
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBZG1pbiIsImdpdmVuX25hbWUiOiJBZG1pbiIsImZhbWlseV9uYW1lIjoiQWRtaW4iLCJqdGkiOiI3OWJjOGJkMC0xOTVmLTQ4ODYtYTNkNy1iOWNhZjExZTFlY2IiLCJleHAiOjIwNDI2NjExMTEsImlzcyI6IkhpZ2hsb2FkU29jaWFsIiwiYXVkIjoiSGlnaGxvYWRTb2NpYWwifQ.ZIu9UVlsbxZoRXPcGctblduSdlLvmsoiFb37FQzUp_c

POST http://{{core_host}}/login
Content-Type: application/json

{
  "id": "Admin",
  "password": "password"
}


### SendMessage
POST http://{{dialogs_host}}/dialog/Admin/send
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Sup Admin"
}

### ListDialogs
GET http://{{dialogs_host}}/dialog/list
Content-Type: application/json
Authorization: Bearer {{token}}

### ListMessages
GET http://{{dialogs_host}}/dialog/User/list
Content-Type: application/json
Authorization: Bearer {{token}}